#!/usr/bin/env bash
#
# ReconTool — interactive VPS installer.
#
# Sets up the Docker container behind an nginx reverse proxy with TLS and
# HTTP basic auth. During the run it asks how you want to terminate TLS:
#   1) your own domain      — real Let's Encrypt certificate
#   2) a free DuckDNS host  — real Let's Encrypt certificate
#   3) a self-signed cert   — reached via https://<vps-ip>, browser warning
#
# Run as root from the repository root on a fresh Debian/Ubuntu VPS:
#   sudo bash scripts/setup-vps.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
NGINX_SITE="/etc/nginx/sites-available/recon-tool"
HTPASSWD="/etc/nginx/.htpasswd"
METADATA_IP="169.254.169.254"

c_info() { printf '\033[36m[*]\033[0m %s\n' "$*"; }
c_ok()   { printf '\033[32m[+]\033[0m %s\n' "$*"; }
c_warn() { printf '\033[33m[!]\033[0m %s\n' "$*"; }
c_err()  { printf '\033[31m[x]\033[0m %s\n' "$*" >&2; }

trap 'c_err "Installation aborted on line $LINENO."' ERR

confirm() {
  local reply
  read -rp "$1 [y/N] " reply
  [[ "$reply" =~ ^[Yy]$ ]]
}

read_nonempty() {
  # read_nonempty "prompt" VARNAME
  local prompt="$1" varname="$2" value=""
  while [ -z "$value" ]; do
    read -rp "$prompt" value
    [ -z "$value" ] && c_warn "This cannot be empty."
  done
  printf -v "$varname" '%s' "$value"
}

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    c_err "Run this script as root: sudo bash scripts/setup-vps.sh"
    exit 1
  fi
}

ensure_prereqs() {
  c_info "Updating package lists and ensuring base tools..."
  apt-get update -qq
  apt-get install -y -qq curl ca-certificates >/dev/null
}

install_docker() {
  if command -v docker >/dev/null 2>&1; then
    c_ok "Docker already installed ($(docker --version))."
    return
  fi
  c_info "Docker is not installed."
  if confirm "Install Docker now via get.docker.com?"; then
    curl -fsSL https://get.docker.com | sh
    c_ok "Docker installed."
  else
    c_err "Docker is required. Aborting."
    exit 1
  fi
}

install_packages() {
  c_info "Installing nginx, certbot, openssl and tools..."
  apt-get install -y -qq nginx certbot python3-certbot-nginx apache2-utils openssl >/dev/null
  c_ok "Packages installed."
}

# The earlier version of the guide suggested dropping whole RFC1918 ranges
# in DOCKER-USER, which breaks container DNS and image builds. Remove any
# such leftover rules so the build can succeed.
fix_egress_rules() {
  local net removed=0
  for net in 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 169.254.0.0/16; do
    while iptables -C DOCKER-USER -d "$net" -j DROP 2>/dev/null; do
      iptables -D DOCKER-USER -d "$net" -j DROP
      removed=1
    done
  done
  [ "$removed" = 1 ] && c_warn "Removed over-broad DOCKER-USER DROP rules (they break container DNS)."
  return 0
}

start_container() {
  c_info "Building and starting the ReconTool container..."
  # Behind a reverse proxy: enable TRUST_PROXY via a compose override so the
  # rate limiter sees the real client IP. This leaves docker-compose.yml clean.
  cat > "$REPO_DIR/docker-compose.override.yml" <<'EOF'
# Generated by scripts/setup-vps.sh — app runs behind an nginx reverse proxy.
services:
  recon-tool:
    environment:
      TRUST_PROXY: "1"
EOF
  ( cd "$REPO_DIR" && docker compose up -d --build )
  c_ok "Container is up (bound to 127.0.0.1:5174)."
}

open_firewall() {
  if command -v ufw >/dev/null 2>&1; then
    ufw allow 80/tcp  >/dev/null 2>&1 || true
    ufw allow 443/tcp >/dev/null 2>&1 || true
    c_ok "UFW: ports 80 and 443 allowed."
  else
    c_warn "ufw not installed — make sure ports 80 and 443 are reachable."
  fi
}

choose_tls_mode() {
  echo
  echo "How should the site be reached?"
  echo "  1) Own domain       — real Let's Encrypt certificate"
  echo "  2) DuckDNS hostname — free, real Let's Encrypt certificate"
  echo "  3) Self-signed      — https://<vps-ip>, one-time browser warning"
  echo
  local choice
  while true; do
    read -rp "Choose 1, 2 or 3: " choice
    case "$choice" in
      1) TLS_MODE="domain"; break ;;
      2) TLS_MODE="duckdns"; break ;;
      3) TLS_MODE="selfsigned"; break ;;
      *) c_warn "Please enter 1, 2 or 3." ;;
    esac
  done
}

get_hostname() {
  case "$TLS_MODE" in
    domain)
      echo
      c_info "Make sure a DNS A record points the host at this VPS (${PUBLIC_IP:-this server})."
      read_nonempty "Enter the (sub)domain, e.g. recon.example.com: " HOST
      ;;
    duckdns)
      echo
      c_warn "First create the hostname at https://www.duckdns.org and set its"
      c_warn "IP to ${PUBLIC_IP:-the public IP of this VPS}."
      read_nonempty "Enter your full DuckDNS hostname, e.g. myrecon.duckdns.org: " HOST
      ;;
    selfsigned)
      HOST="${PUBLIC_IP:-localhost}"
      c_info "Self-signed mode — the site will be reached at https://$HOST"
      ;;
  esac
}

check_dns() {
  [ "$TLS_MODE" = "selfsigned" ] && return 0
  local resolved
  resolved="$(getent hosts "$HOST" | awk '{print $1}' | head -n1 || true)"
  if [ -z "$resolved" ]; then
    c_warn "$HOST does not resolve yet — the certificate request will fail until DNS propagates."
  elif [ -n "${PUBLIC_IP:-}" ] && [ "$resolved" != "$PUBLIC_IP" ]; then
    c_warn "$HOST resolves to $resolved, but this VPS appears to be $PUBLIC_IP."
    c_warn "Let's Encrypt will fail unless the record points here."
  else
    c_ok "$HOST resolves to $resolved."
  fi
  confirm "Continue anyway?" || { c_err "Aborted by user."; exit 1; }
}

setup_auth() {
  echo
  local user
  read_nonempty "Choose a username for the login (HTTP basic auth): " user
  c_info "Now set the password for '$user':"
  htpasswd -c "$HTPASSWD" "$user"
  chown root:www-data "$HTPASSWD" 2>/dev/null || true
  chmod 640 "$HTPASSWD"
  c_ok "Login configured for user '$user'."
}

PROXY_BLOCK=$(cat <<'EOF'
    location / {
        auth_basic           "ReconTool - authorized users only";
        auth_basic_user_file /etc/nginx/.htpasswd;

        proxy_pass         http://127.0.0.1:5174;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
    }
EOF
)

write_nginx_http() {
  # HTTP-only block; `certbot --nginx` upgrades it to HTTPS afterwards.
  cat > "$NGINX_SITE" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $HOST;

$PROXY_BLOCK
}
EOF
  ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/recon-tool
  nginx -t && systemctl reload nginx
  c_ok "nginx site for $HOST enabled."
}

write_nginx_selfsigned() {
  local crt=/etc/ssl/certs/recon-selfsigned.crt
  local key=/etc/ssl/private/recon-selfsigned.key
  c_info "Generating a self-signed certificate for $HOST..."
  openssl req -x509 -nodes -newkey rsa:2048 -days 825 \
    -keyout "$key" -out "$crt" -subj "/CN=$HOST" >/dev/null 2>&1
  cat > "$NGINX_SITE" <<EOF
server {
    listen 80;
    listen [::]:80;
    server_name $HOST;
    return 301 https://\$host\$request_uri;
}
server {
    listen 443 ssl;
    listen [::]:443 ssl;
    server_name $HOST;

    ssl_certificate     $crt;
    ssl_certificate_key $key;

$PROXY_BLOCK
}
EOF
  ln -sf "$NGINX_SITE" /etc/nginx/sites-enabled/recon-tool
  nginx -t && systemctl reload nginx
  c_ok "nginx site with self-signed TLS enabled."
}

run_certbot() {
  local email
  read_nonempty "Email for Let's Encrypt expiry notices: " email
  c_info "Requesting a certificate for $HOST..."
  certbot --nginx -d "$HOST" --non-interactive --agree-tos --redirect -m "$email"
  c_ok "Let's Encrypt certificate installed and HTTP->HTTPS redirect enabled."
}

metadata_block() {
  if ! iptables -C DOCKER-USER -d "$METADATA_IP/32" -j DROP 2>/dev/null; then
    iptables -I DOCKER-USER -d "$METADATA_IP/32" -j DROP
  fi
  cat > /etc/systemd/system/docker-metadata-block.service <<EOF
[Unit]
Description=Block container egress to the cloud metadata IP
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
ExecStart=/bin/sh -c '/usr/sbin/iptables -C DOCKER-USER -d $METADATA_IP/32 -j DROP 2>/dev/null || /usr/sbin/iptables -I DOCKER-USER -d $METADATA_IP/32 -j DROP'

[Install]
WantedBy=multi-user.target
EOF
  systemctl enable docker-metadata-block.service >/dev/null 2>&1 || true
  c_ok "Container egress to $METADATA_IP blocked (persisted via systemd)."
}

main() {
  require_root
  echo "=============================================="
  echo "  ReconTool — VPS installer"
  echo "=============================================="
  PUBLIC_IP="$(curl -fsS https://api.ipify.org 2>/dev/null || echo '')"
  [ -n "$PUBLIC_IP" ] && c_info "Detected public IP: $PUBLIC_IP"

  ensure_prereqs
  install_docker
  install_packages
  fix_egress_rules
  start_container
  open_firewall

  choose_tls_mode
  get_hostname
  setup_auth

  if [ "$TLS_MODE" = "selfsigned" ]; then
    write_nginx_selfsigned
  else
    check_dns
    write_nginx_http
    run_certbot
  fi

  metadata_block

  echo
  c_ok  "Installation complete."
  c_info "Open:  https://$HOST"
  [ "$TLS_MODE" = "selfsigned" ] && c_warn "Accept the one-time browser warning (self-signed certificate)."
  c_info "Logs:  cd $REPO_DIR && docker compose logs -f"
}

main "$@"
