#!/usr/bin/env bash
#
# Switch the deployment from "build from source" to the prebuilt Docker Hub
# image (arid69/recon-tool) and enable Watchtower auto-updates.
#
# Safe to re-run. Run from the repository root:
#   sudo bash scripts/switch-to-prebuilt.sh
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_DIR"

c_info() { printf '\033[36m[*]\033[0m %s\n' "$*"; }
c_ok()   { printf '\033[32m[+]\033[0m %s\n' "$*"; }
c_warn() { printf '\033[33m[!]\033[0m %s\n' "$*"; }
c_err()  { printf '\033[31m[x]\033[0m %s\n' "$*" >&2; }

trap 'c_err "Aborted on line $LINENO."' ERR

if [ "$(id -u)" -ne 0 ]; then
  c_err "Run with sudo: sudo bash scripts/switch-to-prebuilt.sh"
  exit 1
fi

if ! command -v docker >/dev/null 2>&1; then
  c_err "Docker is not installed."
  exit 1
fi

# Build the compose file list — include the host-specific override (TRUST_PROXY
# etc., generated by setup-vps.sh) when it exists.
COMPOSE_FILES=(-f docker-compose.prebuilt.yml)
if [ -f docker-compose.override.yml ]; then
  COMPOSE_FILES+=(-f docker-compose.override.yml)
  c_info "Including docker-compose.override.yml (host-specific settings)."
fi

# 1. Stop and remove the old build-based stack (uses docker-compose.yml).
if [ -f docker-compose.yml ] && docker compose ps -q 2>/dev/null | grep -q .; then
  c_info "Stopping the old source-built stack..."
  docker compose down --remove-orphans || true
fi

# Also kill a stray container with the same name, if any.
if docker ps -a --format '{{.Names}}' | grep -qx 'recon-tool'; then
  c_info "Removing leftover container 'recon-tool'..."
  docker rm -f recon-tool >/dev/null || true
fi

# 2. Remove the locally-built image (the one tagged plain "recon-tool:latest"
#    by the old build: . compose). Keep arid69/recon-tool — that's the new one.
if docker image inspect recon-tool:latest >/dev/null 2>&1; then
  c_info "Removing the locally built image recon-tool:latest..."
  docker image rm recon-tool:latest || true
fi

# 3. Clean up dangling build artefacts to reclaim disk.
c_info "Pruning dangling images and the build cache..."
docker image prune -f >/dev/null || true
docker builder prune -f >/dev/null || true

# 4. Pull the new image from Docker Hub.
c_info "Pulling arid69/recon-tool:latest from Docker Hub..."
docker compose "${COMPOSE_FILES[@]}" --profile autoupdate pull

# 5. Start the prebuilt stack with auto-update enabled.
c_info "Starting the prebuilt stack (with watchtower auto-update)..."
docker compose "${COMPOSE_FILES[@]}" --profile autoupdate up -d

echo
c_ok "Switch complete. Current state:"
docker compose "${COMPOSE_FILES[@]}" --profile autoupdate ps
echo
c_info "Watchtower polls Docker Hub hourly and replaces recon-tool when a"
c_info "newer image is published. Only containers labelled"
c_info "  com.centurylinklabs.watchtower.enable=true"
c_info "will ever be touched."
echo
c_info "Logs:        docker logs -f recon-tool"
c_info "Watchtower:  docker logs -f recon-watchtower"
